/**
 * PDF Document Generator for Agent Output Documents.
 * Formats Markdown document text into a clean printable PDF document
 * with GDG styling and triggers browser PDF download.
 */
export function generatePdfDocument(document: { title: string; content: string; format?: string }) {
  if (typeof window === "undefined") return;

  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to download/print your generated PDF document.");
    return;
  }

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const formattedHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(document.title)} - Generated Document</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    @page {
      size: A4;
      margin: 20mm;
    }
    
    body {
      font-family: 'Inter', system-ui, -apple-system, sans-serif;
      color: #1e293b;
      line-height: 1.6;
      margin: 0;
      padding: 0;
      background-color: #ffffff;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-b: 2px solid #2563eb;
      padding-bottom: 12px;
      margin-bottom: 24px;
    }

    .brand {
      font-size: 14px;
      font-weight: 700;
      color: #2563eb;
      letter-spacing: 0.5px;
    }

    .meta {
      font-size: 11px;
      color: #64748b;
      font-family: monospace;
    }

    h1 {
      font-size: 22px;
      font-weight: 700;
      color: #0f172a;
      margin-top: 0;
      margin-bottom: 16px;
    }

    h2 {
      font-size: 16px;
      font-weight: 700;
      color: #1e40af;
      border-b: 1px solid #e2e8f0;
      padding-bottom: 4px;
      margin-top: 20px;
      margin-bottom: 10px;
    }

    h3 {
      font-size: 14px;
      font-weight: 600;
      color: #334155;
      margin-top: 14px;
      margin-bottom: 6px;
    }

    p {
      font-size: 12px;
      margin-bottom: 10px;
    }

    ul, ol {
      font-size: 12px;
      padding-left: 20px;
      margin-bottom: 12px;
    }

    li {
      margin-bottom: 4px;
    }

    code {
      font-family: monospace;
      background: #f1f5f9;
      padding: 2px 5px;
      border-radius: 4px;
      font-size: 11px;
      color: #0284c7;
    }

    pre {
      background: #0f172a;
      color: #f8fafc;
      padding: 12px;
      border-radius: 8px;
      font-family: monospace;
      font-size: 11px;
      overflow-x: auto;
      white-space: pre-wrap;
    }

    blockquote {
      border-left: 3px solid #8b5cf6;
      background: #f5f3ff;
      margin: 12px 0;
      padding: 8px 12px;
      font-style: italic;
      color: #4c1d95;
      font-size: 12px;
    }

    .footer {
      margin-top: 40px;
      padding-top: 12px;
      border-t: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">GOOGLE DEVELOPER GROUPS • AGENT WORKSHOP</div>
    <div class="meta">Date: ${dateStr}</div>
  </div>

  <h1>${escapeHtml(document.title)}</h1>

  <div class="content">
    ${formatMarkdownToHtml(document.content)}
  </div>

  <div class="footer">
    <div>Generated by OpenAgent AI Platform</div>
    <div>Document Format: PDF</div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 300);
    };
  </script>
</body>
</html>
  `;

  printWindow.document.open();
  printWindow.document.write(formattedHtml);
  printWindow.document.close();
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatMarkdownToHtml(markdown: string): string {
  if (!markdown) return "";

  let html = escapeHtml(markdown);

  // Headers
  html = html.replace(/^### (.*$)/gim, "<h3>$1</h3>");
  html = html.replace(/^## (.*$)/gim, "<h2>$1</h2>");
  html = html.replace(/^# (.*$)/gim, "<h1>$1</h1>");

  // Bold & Italic
  html = html.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.*?)\*/g, "<em>$1</em>");

  // Blockquotes
  html = html.replace(/^&gt; (.*$)/gim, "blockquote>$1</blockquote>");

  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>");
  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");

  // Lists
  html = html.replace(/^\- (.*$)/gim, "<li>$1</li>");
  html = html.replace(/(<li>.*<\/li>)/gim, "<ul>$1</ul>");

  // Paragraphs
  html = html.replace(/\n\n/g, "</p><p>");
  html = `<p>${html}</p>`;

  return html;
}
